version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: "👍"
      enabled: true
      reject_regex: "👎"
    required: 1
    reset_on_push:
      enabled: true
    users:
    - skyzyx
