# https://docs.travis-ci.com/user/languages/php/
# https://docs.travis-ci.com/user/reference/trusty/
# https://docs.travis-ci.com/user/build-environment-updates/
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/deployment/releases/
# https://docs.travis-ci.com/user/deployment/pages/

language: php
dist: trusty
group: edge
php:
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - 'travis_retry composer self-update'
  - 'travis_retry composer install --no-interaction --prefer-source -oa'
  - 'wget https://scrutinizer-ci.com/ocular.phar'
  - 'phpenv rehash'

script:
  - 'mkdir -p build/logs'
  - 'php bin/phpunit -c phpunit.xml.dist'

after_script:
  - 'php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml'

notifications:
  email:
    - 'ryan@ryanparman.com'
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/89f22ac7aa288b13852c'
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
