language: php
dist: trusty
group: edge
php:
  - 7.2
  - nightly

before_script:
  - 'travis_retry composer self-update'
  - 'travis_retry composer install --no-interaction --prefer-source -oa'
  - 'wget https://scrutinizer-ci.com/ocular.phar'
  - 'phpenv rehash'

script:
  - 'mkdir -p build/logs'
  - 'php bin/phpunit -c phpunit.xml.dist'

after_script:
  - 'php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml'

notifications:
  email:
    - 'ryan@ryanparman.com'
